# Site
# repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Shikhar Bharadwaj
title: Research student at IISc (Intelligent Systems Lab)
email: shikharb@iisc.ac.in
phone: '7989962442'

# Social links
github_username:  Shikhar-S
linkedin_username: shikhar-bharadwaj-936791114
codeforces_username: CaptainRubik_

# About Section
# about_title: About Me
about_profile_image: images/me_image.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, I am a research student at IISc, Bangalore. I am interested in Machine Learning, NLP, Computational Geometry and Algorithms. I do competitive programming for fun.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: Achievements
more_content: | # this will include new lines to allow paragraphs
  • **NTSE Scholarship**: Awarded by Govt of India.

  • **INSPIRE Scholarship**: Awarded by Govt of India to top 1% percentile scorers in ISC. 

  • **Merit Scholarship**: Top 2% of Batch in BITS Hyderabad.

  • **Codechef Rating**: Country rank 533/47826, Global Rank 1229/91711 Shikhar

  • **GATE CS**: Rank-107, Score-851

  • **GRE Score**: 330: 169-Q, 161-V, 4 AWA

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
